import 'dart:io';

import 'package:path_provider/path_provider.dart';
import 'package:open_filex/open_filex.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../../providers/session_provider.dart';
import '../../models/session_model.dart';

class PdfService {
  // ===================================================
  // LIVE PROCEDURE PDF
  // ===================================================

  Future<File> generateReport({
    required SessionData session,
    required int totalPresses,
    required double averageForce,
    required double maximumForce,
    required Duration duration,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (context) => [
          pw.Header(level: 0, child: pw.Text('SMART Report')),

          pw.SizedBox(height: 20),

          pw.Text('Surgical Monitoring and Analytics for Real-Time Tracking'),

          pw.Divider(),

          pw.Text(
            'PATIENT INFORMATION',
            style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
          ),

          pw.Text('Patient Name: ${session.patient?.patientName ?? ""}'),
          pw.Text('Patient ID: ${session.patient?.patientId ?? ""}'),
          pw.Text('Diagnosis: ${session.patient?.diagnosis ?? ""}'),

          pw.SizedBox(height: 20),

          pw.Text(
            'DOCTOR INFORMATION',
            style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
          ),

          pw.Text('Doctor Name: ${session.doctor?.doctorName ?? ""}'),
          pw.Text('Doctor ID: ${session.doctor?.doctorId ?? ""}'),
          pw.Text('Department: ${session.doctor?.department ?? ""}'),

          pw.SizedBox(height: 20),

          pw.Text(
            'DEVICE',
            style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
          ),

          pw.Text(session.deviceName ?? ''),

          pw.SizedBox(height: 20),

          pw.Text(
            'PROCEDURE ANALYTICS',
            style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
          ),

          pw.Text('Total Presses: $totalPresses'),
          pw.Text('Average Force: ${averageForce.toStringAsFixed(1)}'),
          pw.Text('Maximum Force: ${maximumForce.toStringAsFixed(1)}'),
          pw.Text('Duration: ${duration.inSeconds} sec'),
        ],
      ),
    );

    final bytes = await pdf.save();

    final dir = await getApplicationDocumentsDirectory();

    final file = File(
      '${dir.path}/SMART_Report_${DateTime.now().millisecondsSinceEpoch}.pdf',
    );

    await file.writeAsBytes(bytes);

    await OpenFilex.open(file.path);

    return file;
  }

  // ===================================================
  // HISTORY PROCEDURE PDF
  // ===================================================

  Future<File> generateSessionReport(SessionModel session) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (context) => [
          pw.Header(level: 0, child: pw.Text('SMART Procedure Report')),

          pw.SizedBox(height: 20),

          pw.Text(
            'PATIENT INFORMATION',
            style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
          ),

          pw.Text('Patient Name: ${session.patientName}'),

          pw.Text('Patient ID: ${session.patientId}'),

          pw.SizedBox(height: 10),

          pw.Text(
            'DOCTOR INFORMATION',
            style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
          ),

          pw.Text('Doctor Name: ${session.doctorName}'),

          pw.Text('Doctor ID: ${session.doctorId}'),

          pw.SizedBox(height: 10),

          pw.Text(
            'DEVICE INFORMATION',
            style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
          ),

          pw.Text('Device Name: ${session.deviceName}'),

          pw.Text('Device ID: ${session.deviceId}'),

          pw.Divider(),

          pw.Text(
            'PROCEDURE ANALYTICS',
            style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
          ),

          pw.Text('Press Count: ${session.totalPressCount}'),

          pw.Text('Average Force: ${session.averageForce.toStringAsFixed(1)}'),

          pw.Text('Maximum Force: ${session.maxForce.toStringAsFixed(1)}'),

          pw.Text('Duration: ${session.durationSeconds}s'),

          pw.SizedBox(height: 10),

          pw.Text('Start Time: ${session.startTime}'),

          pw.Text('End Time: ${session.endTime}'),

          pw.SizedBox(height: 20),

          pw.Text('Generated by SMART Surgical Monitoring System'),
        ],
      ),
    );

    final bytes = await pdf.save();

    final dir = await getApplicationDocumentsDirectory();

    final file = File('${dir.path}/${session.sessionId}.pdf');

    await file.writeAsBytes(bytes);

    await OpenFilex.open(file.path);

    return file;
  }
}
